all: serverCommunicator clientController

serverCommunicator:
	gcc	 -o	serverCommunicator	communicator.c
clientController: 
	gcc	 -o	clientController	controller.c

clean: 
	rm serverCommunicator clientController
